#!/bin/bash

source ~/scripts/inpath  # source the functions

cmd=$1
checkForCmdInPath "$cmd"

case $? in
  0) echo "✅ $cmd is valid and in PATH";;
  1) echo "❌ $cmd is a full path but not executable";;
  2) echo "❌ $cmd not found in PATH";;
  *) echo "⚠️  Unknown result";;
esac

